// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Azure;
using Azure.Core.Pipeline;
using SampleApi.Client.Models;

namespace SampleApi.Client
{
    /// <summary> The FestivalInterpret service client. </summary>
    public partial class FestivalInterpretClient
    {
        private readonly ClientDiagnostics _clientDiagnostics;
        private readonly HttpPipeline _pipeline;
        internal FestivalInterpretRestClient RestClient { get; }

        /// <summary> Initializes a new instance of FestivalInterpretClient for mocking. </summary>
        protected FestivalInterpretClient()
        {
        }

        /// <summary> Initializes a new instance of FestivalInterpretClient. </summary>
        /// <param name="clientDiagnostics"> The handler for diagnostic messaging in the client. </param>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="endpoint"> server parameter. </param>
        internal FestivalInterpretClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri endpoint = null)
        {
            RestClient = new FestivalInterpretRestClient(clientDiagnostics, pipeline, endpoint);
            _clientDiagnostics = clientDiagnostics;
            _pipeline = pipeline;
        }

        /// <param name="body"> The FestivalInterpretCreateUpdate to use. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual async Task<Response<Stream>> CreateAsync(FestivalInterpretCreateUpdate body, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("FestivalInterpretClient.Create");
            scope.Start();
            try
            {
                return await RestClient.CreateAsync(body, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <param name="body"> The FestivalInterpretCreateUpdate to use. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Response<Stream> Create(FestivalInterpretCreateUpdate body, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("FestivalInterpretClient.Create");
            scope.Start();
            try
            {
                return RestClient.Create(body, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <param name="body"> The FestivalInterpretCreateUpdate to use. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual async Task<Response<Stream>> UpdateAsync(FestivalInterpretCreateUpdate body, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("FestivalInterpretClient.Update");
            scope.Start();
            try
            {
                return await RestClient.UpdateAsync(body, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <param name="body"> The FestivalInterpretCreateUpdate to use. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Response<Stream> Update(FestivalInterpretCreateUpdate body, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("FestivalInterpretClient.Update");
            scope.Start();
            try
            {
                return RestClient.Update(body, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <param name="festivalId"> The String to use. </param>
        /// <param name="interpretId"> The String to use. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual async Task<Response<Stream>> DeleteAsync(string festivalId, string interpretId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("FestivalInterpretClient.Delete");
            scope.Start();
            try
            {
                return await RestClient.DeleteAsync(festivalId, interpretId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <param name="festivalId"> The String to use. </param>
        /// <param name="interpretId"> The String to use. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Response<Stream> Delete(string festivalId, string interpretId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("FestivalInterpretClient.Delete");
            scope.Start();
            try
            {
                return RestClient.Delete(festivalId, interpretId, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }
    }
}
