// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Azure;
using Azure.Core.Pipeline;
using SampleApi.Client.Models;

namespace SampleApi.Client
{
    /// <summary> The StageInterpret service client. </summary>
    public partial class StageInterpretClient
    {
        private readonly ClientDiagnostics _clientDiagnostics;
        private readonly HttpPipeline _pipeline;
        internal StageInterpretRestClient RestClient { get; }

        /// <summary> Initializes a new instance of StageInterpretClient for mocking. </summary>
        protected StageInterpretClient()
        {
        }

        /// <summary> Initializes a new instance of StageInterpretClient. </summary>
        /// <param name="clientDiagnostics"> The handler for diagnostic messaging in the client. </param>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="endpoint"> server parameter. </param>
        internal StageInterpretClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri endpoint = null)
        {
            RestClient = new StageInterpretRestClient(clientDiagnostics, pipeline, endpoint);
            _clientDiagnostics = clientDiagnostics;
            _pipeline = pipeline;
        }

        /// <param name="body"> The StageInterpretCreateUpdateDto to use. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual async Task<Response<Stream>> CreateAsync(StageInterpretCreateUpdateDto body, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("StageInterpretClient.Create");
            scope.Start();
            try
            {
                return await RestClient.CreateAsync(body, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <param name="body"> The StageInterpretCreateUpdateDto to use. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Response<Stream> Create(StageInterpretCreateUpdateDto body, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("StageInterpretClient.Create");
            scope.Start();
            try
            {
                return RestClient.Create(body, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <param name="body"> The StageInterpretCreateUpdateDto to use. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual async Task<Response<Stream>> UpdateAsync(StageInterpretCreateUpdateDto body, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("StageInterpretClient.Update");
            scope.Start();
            try
            {
                return await RestClient.UpdateAsync(body, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <param name="body"> The StageInterpretCreateUpdateDto to use. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Response<Stream> Update(StageInterpretCreateUpdateDto body, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("StageInterpretClient.Update");
            scope.Start();
            try
            {
                return RestClient.Update(body, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <param name="stageId"> The String to use. </param>
        /// <param name="interpretId"> The String to use. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual async Task<Response<Stream>> DeleteAsync(string stageId, string interpretId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("StageInterpretClient.Delete");
            scope.Start();
            try
            {
                return await RestClient.DeleteAsync(stageId, interpretId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <param name="stageId"> The String to use. </param>
        /// <param name="interpretId"> The String to use. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Response<Stream> Delete(string stageId, string interpretId, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("StageInterpretClient.Delete");
            scope.Start();
            try
            {
                return RestClient.Delete(stageId, interpretId, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }
    }
}
