// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SampleApi.Client
{
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// </summary>
    public partial interface IFestivalApi : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IFestival.
        /// </summary>
        IFestival Festival { get; }

        /// <summary>
        /// Gets the IFestivalInterpret.
        /// </summary>
        IFestivalInterpret FestivalInterpret { get; }

        /// <summary>
        /// Gets the IInterpret.
        /// </summary>
        IInterpret Interpret { get; }

        /// <summary>
        /// Gets the IReservation.
        /// </summary>
        IReservation Reservation { get; }

        /// <summary>
        /// Gets the IStage.
        /// </summary>
        IStage Stage { get; }

        /// <summary>
        /// Gets the IStageInterpret.
        /// </summary>
        IStageInterpret StageInterpret { get; }

        /// <summary>
        /// Gets the IUser.
        /// </summary>
        IUser User { get; }

    }
}
