// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace SampleApi.Client.Models
{
    /// <summary> The EntityBase. </summary>
    public partial class EntityBase
    {
        /// <summary> Initializes a new instance of EntityBase. </summary>
        public EntityBase()
        {
        }

        public string Id { get; set; }
    }
}
