// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace SampleApi.Client.Models
{
    /// <summary> The FestivalListDto. </summary>
    internal partial class FestivalListDto
    {
        /// <summary> Initializes a new instance of FestivalListDto. </summary>
        internal FestivalListDto()
        {
        }

        public string Name { get; }
        public MusicGenre? Genre { get; }
        public string Country { get; }
        public string LogoUri { get; }
        public string City { get; }
        public bool? IsFestival { get; }
        public DateTimeOffset? Date { get; }
    }
}
