// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace SampleApi.Client.Models
{
    public partial class FestivalInterpretForInterpretDto : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Festival))
            {
                if (Festival != null)
                {
                    writer.WritePropertyName("festival");
                    writer.WriteObjectValue(Festival);
                }
                else
                {
                    writer.WriteNull("festival");
                }
            }
            writer.WriteEndObject();
        }
    }
}
