// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace SampleApi.Client.Models
{
    /// <summary> The FestivalDetailDto. </summary>
    public partial class FestivalDetailDto : EntityBase
    {
        /// <summary> Initializes a new instance of FestivalDetailDto. </summary>
        public FestivalDetailDto()
        {
            StageList = new ChangeTrackingList<StageForFestivalDto>();
            FestivalInterpret = new ChangeTrackingList<FestivalInterpretForFestivalDto>();
        }

        public string Name { get; set; }
        public MusicGenre? Genre { get; set; }
        public string Country { get; set; }
        public string LogoUri { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string Description { get; set; }
        public DateTimeOffset? StartTime { get; set; }
        public DateTimeOffset? EndTime { get; set; }
        public decimal? Price { get; set; }
        public int? Capacity { get; set; }
        public IList<StageForFestivalDto> StageList { get; set; }
        public IList<FestivalInterpretForFestivalDto> FestivalInterpret { get; set; }
    }
}
