// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace SampleApi.Client.Models
{
    /// <summary> The FestivalInterpretForInterpretDto. </summary>
    public partial class FestivalInterpretForInterpretDto
    {
        /// <summary> Initializes a new instance of FestivalInterpretForInterpretDto. </summary>
        public FestivalInterpretForInterpretDto()
        {
        }

        public FestivalInterpretForInterpretDtoFestival Festival { get; set; }
    }
}
