// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace SampleApi.Client.Models
{
    /// <summary> The FestivalInterpretForFestivalDto. </summary>
    public partial class FestivalInterpretForFestivalDto
    {
        /// <summary> Initializes a new instance of FestivalInterpretForFestivalDto. </summary>
        public FestivalInterpretForFestivalDto()
        {
        }

        public FestivalInterpretForFestivalDtoInterpret Interpret { get; set; }
    }
}
