// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace SampleApi.Client.Models
{
    /// <summary> The FestivalInterpretForFestivalDtoInterpret. </summary>
    public partial class FestivalInterpretForFestivalDtoInterpret
    {
        /// <summary> Initializes a new instance of FestivalInterpretForFestivalDtoInterpret. </summary>
        public FestivalInterpretForFestivalDtoInterpret()
        {
        }
    }
}
