// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace SampleApi.Client.Models
{
    /// <summary> The FestivalInterpretCreateUpdate. </summary>
    public partial class FestivalInterpretCreateUpdate
    {
        /// <summary> Initializes a new instance of FestivalInterpretCreateUpdate. </summary>
        public FestivalInterpretCreateUpdate()
        {
        }

        public string FestivalId { get; set; }
        public string InterpretId { get; set; }
    }
}
