// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace SampleApi.Client.Models
{
    /// <summary> The InterpretDetailDto. </summary>
    public partial class InterpretDetailDto : EntityBase
    {
        /// <summary> Initializes a new instance of InterpretDetailDto. </summary>
        public InterpretDetailDto()
        {
            MemberList = new ChangeTrackingList<MemberDetailDto>();
            FestivalInterpret = new ChangeTrackingList<FestivalInterpretForInterpretDto>();
            StageInterpret = new ChangeTrackingList<StageInterpretForInterpretDto>();
        }

        public string Name { get; set; }
        public string LogoUri { get; set; }
        public float? Rating { get; set; }
        public MusicGenre? Genre { get; set; }
        public string Description { get; set; }
        public IList<MemberDetailDto> MemberList { get; set; }
        public IList<FestivalInterpretForInterpretDto> FestivalInterpret { get; set; }
        public IList<StageInterpretForInterpretDto> StageInterpret { get; set; }
    }
}
