// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace SampleApi.Client.Models
{
    public partial class InterpretListDto : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Name))
            {
                if (Name != null)
                {
                    writer.WritePropertyName("name");
                    writer.WriteStringValue(Name);
                }
                else
                {
                    writer.WriteNull("name");
                }
            }
            if (Optional.IsDefined(LogoUri))
            {
                if (LogoUri != null)
                {
                    writer.WritePropertyName("logoUri");
                    writer.WriteStringValue(LogoUri);
                }
                else
                {
                    writer.WriteNull("logoUri");
                }
            }
            if (Optional.IsDefined(Rating))
            {
                writer.WritePropertyName("rating");
                writer.WriteNumberValue(Rating.Value);
            }
            if (Optional.IsDefined(Genre))
            {
                writer.WritePropertyName("genre");
                writer.WriteStringValue(Genre.Value.ToString());
            }
            if (Optional.IsDefined(Id))
            {
                writer.WritePropertyName("id");
                writer.WriteStringValue(Id);
            }
            writer.WriteEndObject();
        }
    }
}
