// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace SampleApi.Client.Models
{
    /// <summary> The InterpretListDto. </summary>
    public partial class InterpretListDto : EntityBase
    {
        /// <summary> Initializes a new instance of InterpretListDto. </summary>
        public InterpretListDto()
        {
        }

        public string Name { get; set; }
        public string LogoUri { get; set; }
        public float? Rating { get; set; }
        public MusicGenre? Genre { get; set; }
    }
}
