// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace SampleApi.Client.Models
{
    /// <summary> The MemberDetailDto. </summary>
    public partial class MemberDetailDto : EntityBase
    {
        /// <summary> Initializes a new instance of MemberDetailDto. </summary>
        public MemberDetailDto()
        {
        }

        public string Name { get; set; }
        public string Surname { get; set; }
    }
}
