// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace SampleApi.Client.Models
{
    /// <summary> The ReservationCreateUpdate. </summary>
    public partial class ReservationCreateUpdate : EntityBase
    {
        /// <summary> Initializes a new instance of ReservationCreateUpdate. </summary>
        public ReservationCreateUpdate()
        {
        }

        public ReservationStatus? State { get; set; }
        public int? Tickets { get; set; }
        public decimal? Price { get; set; }
        public string Description { get; set; }
        public string UserId { get; set; }
        public string FestivalId { get; set; }
    }
}
