// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace SampleApi.Client.Models
{
    /// <summary> The StageInterpretCreateUpdateDto. </summary>
    public partial class StageInterpretCreateUpdateDto
    {
        /// <summary> Initializes a new instance of StageInterpretCreateUpdateDto. </summary>
        public StageInterpretCreateUpdateDto()
        {
        }

        public string InterpretId { get; set; }
        public string StageId { get; set; }
        public int? ConcertLength { get; set; }
        public DateTimeOffset? ConcertStart { get; set; }
        public DateTimeOffset? ConcertEnd { get; set; }
    }
}
