// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace SampleApi.Client.Models
{
    /// <summary> The StageInterpretForInterpretDto. </summary>
    public partial class StageInterpretForInterpretDto
    {
        /// <summary> Initializes a new instance of StageInterpretForInterpretDto. </summary>
        public StageInterpretForInterpretDto()
        {
        }

        public StageInterpretForInterpretDtoStage Stage { get; set; }
        public string StageId { get; set; }
        public int? ConcertLength { get; set; }
        public DateTimeOffset? ConcertStart { get; set; }
        public DateTimeOffset? ConcertEnd { get; set; }
    }
}
