// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace SampleApi.Client.Models
{
    /// <summary> The StageDetailDtoFestival. </summary>
    public partial class StageDetailDtoFestival
    {
        /// <summary> Initializes a new instance of StageDetailDtoFestival. </summary>
        public StageDetailDtoFestival()
        {
        }
    }
}
