// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace SampleApi.Client.Models
{
    /// <summary> The StageDetailDto. </summary>
    public partial class StageDetailDto
    {
        /// <summary> Initializes a new instance of StageDetailDto. </summary>
        public StageDetailDto()
        {
        }

        public string Name { get; set; }
        public int? Capacity { get; set; }
        public StageDetailDtoFestival Festival { get; set; }
    }
}
