// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace SampleApi.Client.Models
{
    /// <summary> The StageForFestivalDto. </summary>
    public partial class StageForFestivalDto : EntityBase
    {
        /// <summary> Initializes a new instance of StageForFestivalDto. </summary>
        public StageForFestivalDto()
        {
        }

        public string Name { get; set; }
        public int? Capacity { get; set; }
    }
}
