// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace SampleApi.Client.Models
{
    /// <summary> The StageCreateDto. </summary>
    public partial class StageCreateDto
    {
        /// <summary> Initializes a new instance of StageCreateDto. </summary>
        public StageCreateDto()
        {
        }

        public string Name { get; set; }
        public int? Capacity { get; set; }
        public string FestivalId { get; set; }
    }
}
