// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace SampleApi.Client.Models
{
    /// <summary> The StageInterpretForInterpretDtoStage. </summary>
    public partial class StageInterpretForInterpretDtoStage
    {
        /// <summary> Initializes a new instance of StageInterpretForInterpretDtoStage. </summary>
        public StageInterpretForInterpretDtoStage()
        {
        }
    }
}
