// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace SampleApi.Client.Models
{
    /// <summary> The UserCreateEditDto. </summary>
    public partial class UserCreateEditDto : EntityBase
    {
        /// <summary> Initializes a new instance of UserCreateEditDto. </summary>
        public UserCreateEditDto()
        {
        }

        public UserRoles? Role { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string Psc { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
