// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace SampleApi.Client.Models
{
    public partial class UserAuthenticateDto : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Username))
            {
                if (Username != null)
                {
                    writer.WritePropertyName("username");
                    writer.WriteStringValue(Username);
                }
                else
                {
                    writer.WriteNull("username");
                }
            }
            if (Optional.IsDefined(Password))
            {
                if (Password != null)
                {
                    writer.WritePropertyName("password");
                    writer.WriteStringValue(Password);
                }
                else
                {
                    writer.WriteNull("password");
                }
            }
            writer.WriteEndObject();
        }
    }
}
