// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace SampleApi.Client.Models
{
    /// <summary> The UserAuthenticateDto. </summary>
    public partial class UserAuthenticateDto
    {
        /// <summary> Initializes a new instance of UserAuthenticateDto. </summary>
        public UserAuthenticateDto()
        {
        }

        public string Username { get; set; }
        public string Password { get; set; }
    }
}
