// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace SampleApi.Client.Models
{
    public partial class FestivalInterpretCreateUpdate : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(FestivalId))
            {
                writer.WritePropertyName("festivalId");
                writer.WriteStringValue(FestivalId);
            }
            if (Optional.IsDefined(InterpretId))
            {
                writer.WritePropertyName("interpretId");
                writer.WriteStringValue(InterpretId);
            }
            writer.WriteEndObject();
        }
    }
}
