// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace SampleApi.Client.Models
{
    /// <summary> The FestivalInterpretForInterpretDtoFestival. </summary>
    public partial class FestivalInterpretForInterpretDtoFestival
    {
        /// <summary> Initializes a new instance of FestivalInterpretForInterpretDtoFestival. </summary>
        public FestivalInterpretForInterpretDtoFestival()
        {
        }
    }
}
