// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SampleApi.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FestivalInterpretCreateUpdate
    {
        /// <summary>
        /// Initializes a new instance of the FestivalInterpretCreateUpdate
        /// class.
        /// </summary>
        public FestivalInterpretCreateUpdate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FestivalInterpretCreateUpdate
        /// class.
        /// </summary>
        public FestivalInterpretCreateUpdate(string festivalId = default(string), string interpretId = default(string))
        {
            FestivalId = festivalId;
            InterpretId = interpretId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "festivalId")]
        public string FestivalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "interpretId")]
        public string InterpretId { get; set; }

    }
}
