// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace SampleApi.Client.Models
{
    public partial class FestivalInterpretForFestivalDto : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Interpret))
            {
                if (Interpret != null)
                {
                    writer.WritePropertyName("interpret");
                    writer.WriteObjectValue(Interpret);
                }
                else
                {
                    writer.WriteNull("interpret");
                }
            }
            writer.WriteEndObject();
        }
    }
}
