// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SampleApi.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FestivalInterpretForInterpretDto
    {
        /// <summary>
        /// Initializes a new instance of the FestivalInterpretForInterpretDto
        /// class.
        /// </summary>
        public FestivalInterpretForInterpretDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FestivalInterpretForInterpretDto
        /// class.
        /// </summary>
        public FestivalInterpretForInterpretDto(object festival = default(object))
        {
            Festival = festival;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "festival")]
        public object Festival { get; set; }

    }
}
