// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;
using System.Globalization;

namespace SampleApi.Client.Models
{
    /// <summary> The MusicGenre. </summary>
    public readonly partial struct MusicGenre : IEquatable<MusicGenre>
    {
        private readonly int _value;

        /// <summary> Determines if two <see cref="MusicGenre"/> values are the same. </summary>
        public MusicGenre(int value)
        {
            _value = value;
        }

        private const int ZeroValue = 0;
        private const int OneValue = 1;
        private const int TwoValue = 2;
        private const int ThreeValue = 3;
        private const int FourValue = 4;
        private const int FiveValue = 5;

        /// <summary> 0. </summary>
        public static MusicGenre Zero { get; } = new MusicGenre(ZeroValue);
        /// <summary> 1. </summary>
        public static MusicGenre One { get; } = new MusicGenre(OneValue);
        /// <summary> 2. </summary>
        public static MusicGenre Two { get; } = new MusicGenre(TwoValue);
        /// <summary> 3. </summary>
        public static MusicGenre Three { get; } = new MusicGenre(ThreeValue);
        /// <summary> 4. </summary>
        public static MusicGenre Four { get; } = new MusicGenre(FourValue);
        /// <summary> 5. </summary>
        public static MusicGenre Five { get; } = new MusicGenre(FiveValue);
        /// <summary> Determines if two <see cref="MusicGenre"/> values are the same. </summary>
        public static bool operator ==(MusicGenre left, MusicGenre right) => left.Equals(right);
        /// <summary> Determines if two <see cref="MusicGenre"/> values are not the same. </summary>
        public static bool operator !=(MusicGenre left, MusicGenre right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="MusicGenre"/>. </summary>
        public static implicit operator MusicGenre(int value) => new MusicGenre(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is MusicGenre other && Equals(other);
        /// <inheritdoc />
        public bool Equals(MusicGenre other) => Equals(_value, other._value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value.GetHashCode();
        /// <inheritdoc />
        public override string ToString() => _value.ToString(CultureInfo.InvariantCulture);
    }
}
