// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;
using System.Globalization;

namespace SampleApi.Client.Models
{
    /// <summary> The ReservationStatus. </summary>
    public readonly partial struct ReservationStatus : IEquatable<ReservationStatus>
    {
        private readonly int _value;

        /// <summary> Determines if two <see cref="ReservationStatus"/> values are the same. </summary>
        public ReservationStatus(int value)
        {
            _value = value;
        }

        private const int ZeroValue = 0;
        private const int OneValue = 1;
        private const int TwoValue = 2;
        private const int ThreeValue = 3;

        /// <summary> 0. </summary>
        public static ReservationStatus Zero { get; } = new ReservationStatus(ZeroValue);
        /// <summary> 1. </summary>
        public static ReservationStatus One { get; } = new ReservationStatus(OneValue);
        /// <summary> 2. </summary>
        public static ReservationStatus Two { get; } = new ReservationStatus(TwoValue);
        /// <summary> 3. </summary>
        public static ReservationStatus Three { get; } = new ReservationStatus(ThreeValue);
        /// <summary> Determines if two <see cref="ReservationStatus"/> values are the same. </summary>
        public static bool operator ==(ReservationStatus left, ReservationStatus right) => left.Equals(right);
        /// <summary> Determines if two <see cref="ReservationStatus"/> values are not the same. </summary>
        public static bool operator !=(ReservationStatus left, ReservationStatus right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="ReservationStatus"/>. </summary>
        public static implicit operator ReservationStatus(int value) => new ReservationStatus(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ReservationStatus other && Equals(other);
        /// <inheritdoc />
        public bool Equals(ReservationStatus other) => Equals(_value, other._value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value.GetHashCode();
        /// <inheritdoc />
        public override string ToString() => _value.ToString(CultureInfo.InvariantCulture);
    }
}
