// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SampleApi.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class StageForFestivalDto : EntityBase
    {
        /// <summary>
        /// Initializes a new instance of the StageForFestivalDto class.
        /// </summary>
        public StageForFestivalDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the StageForFestivalDto class.
        /// </summary>
        public StageForFestivalDto(string id = default(string), string name = default(string), int? capacity = default(int?))
            : base(id)
        {
            Name = name;
            Capacity = capacity;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "capacity")]
        public int? Capacity { get; set; }

    }
}
