// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SampleApi.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class StageInterpretForInterpretDto
    {
        /// <summary>
        /// Initializes a new instance of the StageInterpretForInterpretDto
        /// class.
        /// </summary>
        public StageInterpretForInterpretDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the StageInterpretForInterpretDto
        /// class.
        /// </summary>
        public StageInterpretForInterpretDto(object stage = default(object), string stageId = default(string), int? concertLength = default(int?), System.DateTimeOffset? concertStart = default(System.DateTimeOffset?), System.DateTimeOffset? concertEnd = default(System.DateTimeOffset?))
        {
            Stage = stage;
            StageId = stageId;
            ConcertLength = concertLength;
            ConcertStart = concertStart;
            ConcertEnd = concertEnd;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stage")]
        public object Stage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stageId")]
        public string StageId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "concertLength")]
        public int? ConcertLength { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "concertStart")]
        public System.DateTimeOffset? ConcertStart { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "concertEnd")]
        public System.DateTimeOffset? ConcertEnd { get; set; }

    }
}
