// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SampleApi.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class StageCreateDto
    {
        /// <summary>
        /// Initializes a new instance of the StageCreateDto class.
        /// </summary>
        public StageCreateDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the StageCreateDto class.
        /// </summary>
        public StageCreateDto(string name = default(string), int? capacity = default(int?), string festivalId = default(string))
        {
            Name = name;
            Capacity = capacity;
            FestivalId = festivalId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "capacity")]
        public int? Capacity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "festivalId")]
        public string FestivalId { get; set; }

    }
}
