// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SampleApi.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class StageForInterpretDto
    {
        /// <summary>
        /// Initializes a new instance of the StageForInterpretDto class.
        /// </summary>
        public StageForInterpretDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the StageForInterpretDto class.
        /// </summary>
        public StageForInterpretDto(string name = default(string), int? capacity = default(int?), string festivalName = default(string), IList<StageInterpretForInterpretDto> stageInterpret = default(IList<StageInterpretForInterpretDto>))
        {
            Name = name;
            Capacity = capacity;
            FestivalName = festivalName;
            StageInterpret = stageInterpret;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "capacity")]
        public int? Capacity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "festivalName")]
        public string FestivalName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stageInterpret")]
        public IList<StageInterpretForInterpretDto> StageInterpret { get; set; }

    }
}
