// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SampleApi.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UserCreateEditDto : EntityBase
    {
        /// <summary>
        /// Initializes a new instance of the UserCreateEditDto class.
        /// </summary>
        public UserCreateEditDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UserCreateEditDto class.
        /// </summary>
        public UserCreateEditDto(string id = default(string), int? role = default(int?), string name = default(string), string surname = default(string), string country = default(string), string city = default(string), string street = default(string), string psc = default(string), string email = default(string), string username = default(string), string password = default(string))
            : base(id)
        {
            Role = role;
            Name = name;
            Surname = surname;
            Country = country;
            City = city;
            Street = street;
            Psc = psc;
            Email = email;
            Username = username;
            Password = password;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "role")]
        public int? Role { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "surname")]
        public string Surname { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "country")]
        public string Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "city")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "street")]
        public string Street { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "psc")]
        public string Psc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "username")]
        public string Username { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

    }
}
