// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SampleApi.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UserAuthenticateDto
    {
        /// <summary>
        /// Initializes a new instance of the UserAuthenticateDto class.
        /// </summary>
        public UserAuthenticateDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UserAuthenticateDto class.
        /// </summary>
        public UserAuthenticateDto(string username = default(string), string password = default(string))
        {
            Username = username;
            Password = password;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "username")]
        public string Username { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

    }
}
