// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace SampleApi.Client.Models
{
    public partial class UserCreateEditDto : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Role))
            {
                writer.WritePropertyName("role");
                writer.WriteStringValue(Role.Value.ToString());
            }
            if (Optional.IsDefined(Name))
            {
                if (Name != null)
                {
                    writer.WritePropertyName("name");
                    writer.WriteStringValue(Name);
                }
                else
                {
                    writer.WriteNull("name");
                }
            }
            if (Optional.IsDefined(Surname))
            {
                if (Surname != null)
                {
                    writer.WritePropertyName("surname");
                    writer.WriteStringValue(Surname);
                }
                else
                {
                    writer.WriteNull("surname");
                }
            }
            if (Optional.IsDefined(Country))
            {
                if (Country != null)
                {
                    writer.WritePropertyName("country");
                    writer.WriteStringValue(Country);
                }
                else
                {
                    writer.WriteNull("country");
                }
            }
            if (Optional.IsDefined(City))
            {
                if (City != null)
                {
                    writer.WritePropertyName("city");
                    writer.WriteStringValue(City);
                }
                else
                {
                    writer.WriteNull("city");
                }
            }
            if (Optional.IsDefined(Street))
            {
                if (Street != null)
                {
                    writer.WritePropertyName("street");
                    writer.WriteStringValue(Street);
                }
                else
                {
                    writer.WriteNull("street");
                }
            }
            if (Optional.IsDefined(Psc))
            {
                if (Psc != null)
                {
                    writer.WritePropertyName("psc");
                    writer.WriteStringValue(Psc);
                }
                else
                {
                    writer.WriteNull("psc");
                }
            }
            if (Optional.IsDefined(Email))
            {
                if (Email != null)
                {
                    writer.WritePropertyName("email");
                    writer.WriteStringValue(Email);
                }
                else
                {
                    writer.WriteNull("email");
                }
            }
            if (Optional.IsDefined(Username))
            {
                if (Username != null)
                {
                    writer.WritePropertyName("username");
                    writer.WriteStringValue(Username);
                }
                else
                {
                    writer.WriteNull("username");
                }
            }
            if (Optional.IsDefined(Password))
            {
                if (Password != null)
                {
                    writer.WritePropertyName("password");
                    writer.WriteStringValue(Password);
                }
                else
                {
                    writer.WriteNull("password");
                }
            }
            if (Optional.IsDefined(Id))
            {
                writer.WritePropertyName("id");
                writer.WriteStringValue(Id);
            }
            writer.WriteEndObject();
        }
    }
}
